// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Basename(arg1:string):Promise<string>;

export function CreateEntry(arg1:string,arg2:string,arg3:boolean):Promise<main.FileEntry>;

export function DeleteEntry(arg1:string):Promise<void>;

export function EnsureLinkID(arg1:string):Promise<string>;

export function ExportPdf(arg1:string,arg2:string):Promise<void>;

export function FileExists(arg1:string):Promise<boolean>;

export function GetInitialFile():Promise<string>;

export function GetSettings():Promise<main.Settings>;

export function GetSyncStatus():Promise<main.SyncStatus>;

export function ListDir(arg1:string):Promise<Array<main.FileEntry>>;

export function MigrateRootDir():Promise<main.Settings>;

export function MoveEntry(arg1:string,arg2:string):Promise<string>;

export function OpenAnyFileDialog():Promise<string>;

export function OpenFileDialog(arg1:string):Promise<string>;

export function OpenURL(arg1:string):Promise<void>;

export function OpenWithDefaultApp(arg1:string):Promise<void>;

export function ReadFile(arg1:string):Promise<string>;

export function RenameEntry(arg1:string,arg2:string):Promise<string>;

export function ResolveLinkID(arg1:string):Promise<string>;

export function RevealInExplorer(arg1:string):Promise<void>;

export function SaveAppSettings(arg1:string,arg2:boolean):Promise<main.Settings>;

export function SaveFileDialog(arg1:string,arg2:string):Promise<string>;

export function SaveOpenTabs(arg1:Array<string>,arg2:string):Promise<void>;

export function SavePdfDialog(arg1:string,arg2:string):Promise<string>;

export function SaveSyncSettings(arg1:boolean,arg2:string,arg3:string,arg4:string,arg5:number):Promise<main.Settings>;

export function SelectRootDir():Promise<main.Settings>;

export function SyncNow():Promise<main.SyncResult>;

export function TestSyncConnection(arg1:string,arg2:string,arg3:string):Promise<string>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
