// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Basename(arg1:string):Promise<string>;

export function CreateEntry(arg1:string,arg2:string,arg3:boolean):Promise<main.FileEntry>;

export function DeleteEntry(arg1:string):Promise<void>;

export function FileExists(arg1:string):Promise<boolean>;

export function GetInitialFile():Promise<string>;

export function GetSettings():Promise<main.Settings>;

export function ListDir(arg1:string):Promise<Array<main.FileEntry>>;

export function MigrateRootDir():Promise<main.Settings>;

export function MoveEntry(arg1:string,arg2:string):Promise<string>;

export function OpenAnyFileDialog():Promise<string>;

export function OpenFileDialog(arg1:string):Promise<string>;

export function OpenURL(arg1:string):Promise<void>;

export function OpenWithDefaultApp(arg1:string):Promise<void>;

export function ReadFile(arg1:string):Promise<string>;

export function RenameEntry(arg1:string,arg2:string):Promise<string>;

export function SaveFileDialog(arg1:string,arg2:string):Promise<string>;

export function SaveOpenTabs(arg1:Array<string>,arg2:string):Promise<void>;

export function SelectRootDir():Promise<main.Settings>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
