// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDictionaryWord(arg1) {
  return window['go']['main']['App']['AddDictionaryWord'](arg1);
}

export function Basename(arg1) {
  return window['go']['main']['App']['Basename'](arg1);
}

export function CreateEntry(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateEntry'](arg1, arg2, arg3);
}

export function DeleteEntry(arg1) {
  return window['go']['main']['App']['DeleteEntry'](arg1);
}

export function EnsureLinkID(arg1) {
  return window['go']['main']['App']['EnsureLinkID'](arg1);
}

export function ExportPdf(arg1, arg2) {
  return window['go']['main']['App']['ExportPdf'](arg1, arg2);
}

export function FileExists(arg1) {
  return window['go']['main']['App']['FileExists'](arg1);
}

export function GetInitialFile() {
  return window['go']['main']['App']['GetInitialFile']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSyncStatus() {
  return window['go']['main']['App']['GetSyncStatus']();
}

export function ListDir(arg1) {
  return window['go']['main']['App']['ListDir'](arg1);
}

export function MigrateRootDir() {
  return window['go']['main']['App']['MigrateRootDir']();
}

export function MoveEntry(arg1, arg2) {
  return window['go']['main']['App']['MoveEntry'](arg1, arg2);
}

export function OpenAnyFileDialog() {
  return window['go']['main']['App']['OpenAnyFileDialog']();
}

export function OpenFileDialog(arg1) {
  return window['go']['main']['App']['OpenFileDialog'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function OpenWithDefaultApp(arg1) {
  return window['go']['main']['App']['OpenWithDefaultApp'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function RenameEntry(arg1, arg2) {
  return window['go']['main']['App']['RenameEntry'](arg1, arg2);
}

export function ResolveLinkID(arg1) {
  return window['go']['main']['App']['ResolveLinkID'](arg1);
}

export function RevealInExplorer(arg1) {
  return window['go']['main']['App']['RevealInExplorer'](arg1);
}

export function SaveAppSettings(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveAppSettings'](arg1, arg2, arg3);
}

export function SaveFileDialog(arg1, arg2) {
  return window['go']['main']['App']['SaveFileDialog'](arg1, arg2);
}

export function SaveOpenTabs(arg1, arg2) {
  return window['go']['main']['App']['SaveOpenTabs'](arg1, arg2);
}

export function SavePdfDialog(arg1, arg2) {
  return window['go']['main']['App']['SavePdfDialog'](arg1, arg2);
}

export function SaveSyncSettings(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SaveSyncSettings'](arg1, arg2, arg3, arg4, arg5);
}

export function SelectRootDir() {
  return window['go']['main']['App']['SelectRootDir']();
}

export function SyncNow() {
  return window['go']['main']['App']['SyncNow']();
}

export function TestSyncConnection(arg1, arg2, arg3) {
  return window['go']['main']['App']['TestSyncConnection'](arg1, arg2, arg3);
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}
